<?php

declare(strict_types=1);

namespace Elm;

/**
 * Provides the 'Learning schedule type' controlled vocabulary.
 *
 * @link https://op.europa.eu/en/web/eu-vocabularies/concept-scheme/-/resource?uri=http://data.europa.eu/snb/learning-schedule/25831c2
 *
 * This file is automatically generated by the build script at the project root
 * so any manual changes may be lost at build time.
 */
final class LearningScheduleType extends ControlledVocabulary
{
    /**
     * Get vocabulary name.
     *
     * Returns the name of the ELM controlled vocabulary.
     *
     * @return string
     **/
    public function getName(): string
    {
        return 'Learning schedule type';
    }

    /**
     * Get vocabulary.
     *
     * Returns the content of the controlled vocabulary.
     *
     * @return array<string, array<string, string|null>>
     **/
    public function getVocabulary(): array
    {
        return static::list();
    }

    /**
     * Curated vocabulary.
     *
     * Returns the content of the controlled vocabulary.
     *
     * @return array<string, array<string, string|null>>
     **/
    public static function list(): array
    {
        return [
            '67395e6b5a' => [
                'label' => 'Part time light',
                'validSince' => '2020-06-24',
                'validUntil' => null,
                'definition' => 'Part time light (less than 8 hours)',
            ],
            '72a0ab92fa' => [
                'label' => 'Full time ',
                'validSince' => '2020-06-24',
                'validUntil' => null,
                'definition' => 'Full time (more then 30 hours)',
            ],
            'f230bae523' => [
                'label' => 'Part time intensive ',
                'validSince' => '2020-06-24',
                'validUntil' => null,
                'definition' => 'Part time intensive (8 to 30 hours)',
            ],
        ];
    }
}
